name: Update Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pytz requests

      - run: python generate_calendar.py

      - uses: EndBug/add-and-commit@v9
        with:
          add: "calendar.ics"
          message: "update calendar"
